version: '3.9'

services:
  kotlinapp:
    container_name: kotlin-api-rest
    image: kotlinapp:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080" 
    environment:
      DB_URL: jdbc:postgresql://db:5432/dbkotlin
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - db
  db:
    container_name: dbkotlin
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbkotlin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
